scrape_configs:
  - job_name: 'spring-boot-demo-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['192.168.0.24:8081']
        labels:
          application: 'SSBPrometheus'